### ISSUE TITLE
Bug: Indexing Internal Error

### ISSUE THREAD

**Issue by RevenantOne** [somebeaver/Cardinal-Project#4]
I'm getting the following error when trying to scan my library. The '75104' count for indexed tracks is also stuck despite restarting the server and running it as an admin. This only appears when I close and reopen the window once I notice it's stuck.

![image](https://user-images.githubusercontent.com/3936764/122405197-c0f0da80-cf77-11eb-8b83-d8a4ecb2cfb5.png)

Here's what the DevTools say

![image](https://user-images.githubusercontent.com/3936764/122405923-5a1ff100-cf78-11eb-8004-f5af75146d0c.png)

Is there anyway to tell what the indexer is getting stuck on.

**Comment by somebeaver** [comment]
If I'm understanding correctly, if you restart the server and run the indexing, it will crash around file 75,104?

The "ALREADYRUNNING" line means that the server is refusing to start a new indexing run because one is already running. This can happens if the indexing code crashes.

If you restart the server and run it again, does it skip the first ~75k files and then immediately crash when it encounters the problematic file? If so, it should be possible to determine which file is causing the issue by checking the console and seeing which file was *last* indexed (so, the problematic one will be the next file).

If you are willing to join the Cardinal Discord, I could take a look at the particular file and see what's going on. Sorry for the inconvenience.

**Comment by RevenantOne** [comment]
When I restart the server and the indexing it will take ~35 minutes before the it gui shows that files are now being skipped, and then another ~10 mins to get to the problematic file.

I've attached the full log of Cardinal is reporting.
[Cardinal.log](https://github.com/somebeaver/Cardinal-Project/files/6671148/Cardinal.log)

Yeah no problem, I'll join soon.

**Comment by somebeaver** [comment]
Added `beforeFileSync` and `beforeFileImport` output to the console to make it easy to see which file is causing a crash.
